### ISSUE TITLE
Generate and publish update bundle 1.0 of extension bundle 

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-extension-bundles#13]

**Comment by anthonychu** [comment]
Would be great to get the PowerShell templates in here as well. Linking to https://github.com/Azure/azure-functions-templates/pull/940 so we can track them together.

**Comment by fabiocav** [comment]
This is currently just waiting on rapid update.

**Comment by soninaren** [comment]
> Would be great to get the PowerShell templates in here as well. Linking to [Azure/azure-functions-templates#940](https://github.com/Azure/azure-functions-templates/pull/940) so we can track them together.

The powershell templates have been included in the bundle

**Comment by Josh-a-e** [comment]
Hi, is this likely to get released any time soon?

At present, I'm blocked by "Microsoft.Azure.WebJobs.Extensions.Storage" being locked to 3.0.10 when there's a fix in 3.0.11 that I need (issue here: https://github.com/microsoft/vscode-azurefunctions/issues/1725)

More broadly, it would be really useful to be able to manage the extensions contained in the bundle in the host.json - (I think this is what this issue is referencing https://github.com/Azure/azure-functions-core-tools/issues/1913)/

Thanks!

**Comment by anthonychu** [comment]
@soninaren might be able to provide an update.

@Josh-a-e The Core Tools issue you linked to is about changing the bundle version your app is using. It sounds like you are referring to an ability to specifically pick the extensions versions your app is using. This is not supported with bundles. Bundles are meant to be a set of extensions that are known to work together. If you want to select exactly what extensions you want to use, you need to opt-out of bundles and [manually install extensions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=linux%2Ccsharp%2Cbash#register-individual-extensions).

**Comment by Josh-a-e** [comment]
@soninaren Hey, thanks, yeah I did look at that option, but it requires the dotnet tool chain (I’m running both python & node already), so instead I’ve ended up opting out of the data lake blobs for regular ones until 3.0.11 gets added here.

Any rough idea of when that might be?

Thanks again

**Comment by fabiocav** [comment]
Moving to sprint 76 as deployment should be unblocked then.

**Comment by fabiocav** [comment]
Closing as resolved.
