### ISSUE TITLE
Bundle version 3.5.0 not available?

### ISSUE THREAD

**Issue by smafre** [Azure/azure-functions-extension-bundles#135]
I see version 3.5.0 has been released, but I still get version 3.3.0 when starting my function app. Seems like version 3.5.0 isn't available?

I get this output when starting my function app:
`Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json`

The list of versions on that URL does not include 3.5.0.

**Comment by smafre** [comment]
/cc @soninaren

Anyone reading these issues? It's kind of urgent for us to get this issue of ours fixed.

**Comment by soninaren** [comment]
> /cc @soninaren
> 
> Anyone reading these issues? It's kind of urgent for us to get this issue of ours fixed.

Apologies for a delayed response here. We are in the process of releasing bundle version 3.5.0. I think one of the release steps was ordered incorrectly which created the release of GitHub much sooner than expected. We have updated the release process since then. Going to remove the release from GitHub until it is actually released as well.
