### ISSUE TITLE
Generate and publish version 2.0 of extension bundle

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-extension-bundles#7]

**Comment by pmihaylov** [comment]
:+1: 
If possible upgrade **Microsoft.Azure.WebJobs.Extensions.** to 2.0.0

**Comment by fabiocav** [comment]
@soninaren should this be in the current sprint?

**Comment by Josh-a-e** [comment]
Hi, is this likely to get released any time soon?

At present, I'm blocked by "Microsoft.Azure.WebJobs.Extensions.Storage" being locked to 3.0.10 when there's a fix in 3.0.11 that I need (issue here: https://github.com/microsoft/vscode-azurefunctions/issues/1725)

More broadly, it would be really useful to be able to manage the extensions contained in the bundle in the host.json - (I think this is what this issue is referencing https://github.com/Azure/azure-functions-core-tools/issues/1913)/

Thanks!

**Comment by fabiocav** [comment]
Moving to triage while we're blocked on storage preview

**Comment by fabiocav** [comment]
In validation. Should be available within the next couple of days.

**Comment by acomley** [comment]
Any update on this?

**Comment by soninaren** [comment]
The deployment for bundle 2.0 is in progress and has made it through partially. The deployment would 2 weeks at the minimum to complete. Will post an update once the deployment is complete.

**Comment by fabiocav** [comment]
Linux deployment is still pending. Moving this to sprint 82.

**Comment by fabiocav** [comment]
Deployment is now done. The remaining bundles changes can be pushed out.

**Comment by fabiocav** [comment]
@anthonychu - FYI, once the artifacts are released, we can publish the documentation updates.

**Comment by soninaren** [comment]
The release is now complete.
